### ISSUE TITLE
Profile - W3C Checking: 1 Error.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Argyle-Furniture-Designs#1]
https://validator.w3.org/nu/?doc=http%3A%2F%2Fargylefurniture-imp.stage.titanweb.com.au%2Fprofile%2F
![image](https://cloud.githubusercontent.com/assets/13363508/16325671/a1053d4e-39f2-11e6-8dfd-d6fa93be4b52.png)

**Comment by mikay-titan** [comment]
Note: Not a bug. User Error.
