### ISSUE TITLE
Enquiry Form: Anti-spam honeypot isn't enabled.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Argyle-Furniture-Designs#5]
![image](https://cloud.githubusercontent.com/assets/13363508/16326311/1384dde8-39f8-11e6-9891-8196ad48f3b3.png)

**Comment by mikay-titan** [comment]
Anti-spam honeypot is disabled to avoid redundant functionality since there is already a Captcha found inside the form.
