### ISSUE TITLE
Product Single page - Enquiry form: Filling up the form fields except for the Captcha then clicking Submit, the item uploaded will be shown also in the Request a Quote form.

### ISSUE THREAD

**Issue by maehtitan** [titan-cebu/Argyle-Furniture-Designs#7]
**Also when uploading an item in the "Request a Quote"  form and then clicking the submit button will also reflect in Enquiry form**

![image](https://cloud.githubusercontent.com/assets/13363508/16326524/f5e04456-39f9-11e6-8b9c-ceca4df1dffc.png)
![image](https://cloud.githubusercontent.com/assets/13363508/16327004/489f8bbc-39fe-11e6-9fb3-957cc8aefeb2.png)

**Comment by mikay-titan** [comment]
Note: Changed Captcha used since the old one has conflict with ajax functionality. Enabled ajax so that uploaded item in a certain form won't show in the other form.
